services:
  web:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
